version: "3"
services:
  redis:
    image: redis:4-alpine
    ports:
      - "6379"
  node:
    image: node:8-alpine
    volumes:
      - .:/opt/app
    working_dir: /opt/app
    command: node count.js
